# ---------------------------------------------------------------------------
# FloatRasterToPolygon.py
# Created on: Tue Sep 30 2008 01:15:01 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

#E:/GIS/us_water/data.gdb/Precipitation/Raster.OBJECTID=5 3 E:/GIS/us_water/data.gdb/test_1

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create(9.3)
gp.overwriteoutput = 1

try:
    toolShareFolder = os.path.dirname(sys.path[0]) + os.path.sep
    scratchGDB = toolShareFolder + "Scratch" + os.path.sep + "scratch.gdb"
    scratchWorkspace = gp.scratchworkspace or scratchGDB
    
    inputRaster = sys.argv[1]
    decimalPlaces = sys.argv[2]
    outputFC = sys.argv[3]
    factor = pow(10, float(decimalPlaces))
    
    gp.CheckOutExtension("spatial")
    
    timesRaster = gp.createscratchname("times", "", "RasterDataset", scratchWorkspace)
    intRaster = gp.createscratchname("integer", "", "RasterDataset", scratchWorkspace)
    
    gp.Times_sa(inputRaster, factor, timesRaster)
    gp.Int_sa(timesRaster, intRaster)
    gp.RasterToPolygon_conversion(intRaster, outputFC, "SIMPLIFY", "")
    gp.AddField_management(outputFC, "Value", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
    gp.CalculateField_management(outputFC, "Value", "[GRIDCODE] / " + str(factor), "VB", "")
    gp.DeleteField_management(outputFC, "ID;GRIDCODE")
    gp.Delete_management(timesRaster, "RasterDataset")
    gp.Delete_management(intRaster, "RasterDataset")
    gp.CheckInExtension("spatial")
except Exception, err:
    gp.AddError(str(err))
    gp.AddError(gp.getmessages(2))