# ---------------------------------------------------------------------------
# RasterCollectionToPoints.py
# Created on: Fri Oct 03 2008 02:30:52 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

#E:/GIS/us_water/precip_monthly.gdb/jan_daily_average;E:/GIS/us_water/precip_monthly.gdb/feb_daily_average E:/GIS/us_water/precip_monthly.gdb/test_1

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create(9.3)
gp.overwriteoutput = 1

try:
    toolShareFolder = os.path.dirname(sys.path[0]) + os.path.sep
    scratchGDB = toolShareFolder + "Scratch" + os.path.sep + "scratch.gdb"
    scratchWorkspace = gp.scratchworkspace or scratchGDB
    
    inputRasters = sys.argv[1]
    outputFC = sys.argv[2]
    
    gp.CheckOutExtension("spatial")
    
    sampleTable = gp.createscratchname("samples", "", "Table", scratchWorkspace)
    tempFC = gp.createscratchname("points", "", "FeatureClass", scratchWorkspace)
    inputRasterList = inputRasters.split(";")
    
    # Convert the first raster to points
    gp.addmessage("Converting to points...")
    gp.RasterToPoint_conversion(inputRasterList[0], tempFC, "")
    
    # Sample all the rasters at those points
    gp.addmessage("Sampling rasters...")
    gp.Sample_sa(inputRasters, tempFC, sampleTable, "NEAREST")
    
    # Join the sample table to the points
    gp.addmessage("Joining sample table to points...")
    fields = "; ".join(map(lambda field: field.Name, gp.ListFields(sampleTable, "g_*")))
    gp.JoinField_management(tempFC, "POINTID", sampleTable, "OBJECTID", fields)

    gp.addmessage("Exporting result...")
    fieldmappings = gp.createobject("FieldMappings");
    def addMapping (srcField, destFieldName):
        fieldmap = gp.createobject("FieldMap")
        fieldmap.addinputfield(tempFC, srcField.Name)
        outfield = fieldmap.OutputField
        outfield.Name = destFieldName
        outfield.AliasName = destFieldName
        fieldmap.OutputField = outfield
        fieldmappings.addfieldmap(fieldmap)
        return destFieldName
    srcFields = gp.ListFields(tempFC, "G_*")
    newNames = map(lambda p: os.path.split(p)[1], inputRasterList)
    map(addMapping, srcFields, newNames)
    gp.Merge_management(tempFC, outputFC, fieldmappings)

    gp.addmessage("Cleaning up...")
    gp.Delete_management(sampleTable, "Table")
    gp.Delete_management(tempFC, "FeatureClass")
    
    gp.CheckInExtension("spatial")
except Exception, err:
    gp.AddError(str(err))
    gp.AddError(gp.getmessages(2))

