# ---------------------------------------------------------------------------
# FloatRasterToPolygon.py
# Created on: Tue Sep 30 2008 01:15:01 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

#E:/GIS/us_water/data.gdb/Precipitation/Raster.OBJECTID=5 3 E:/GIS/us_water/data.gdb/test_1

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create(9.3)
gp.overwriteoutput = 1

try:
    inputRaster = sys.argv[1]
    decimalPlaces = sys.argv[2]
    outputFC = sys.argv[3]
    factor = pow(10, float(decimalPlaces))
    
    gp.CheckOutExtension("spatial")
    gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Spatial Analyst Tools.tbx")
    gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Conversion Tools.tbx")
    gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")
    tempDir = gp.scratchworkspace or gp.GetSystemEnvironment("TEMP")
    
    timesRaster = gp.createscratchname("times", "", "RasterDataset", tempDir)
    intRaster = gp.createscratchname("integer", "", "RasterDataset", tempDir)
    
    gp.Times_sa(inputRaster, factor, timesRaster)
    gp.Int_sa(timesRaster, intRaster)
    gp.RasterToPolygon_conversion(intRaster, outputFC, "SIMPLIFY", "")
    gp.AddField_management(outputFC, "Value", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
    gp.CalculateField_management(outputFC, "Value", "[GRIDCODE] / " + str(factor), "VB", "")
    gp.DeleteField_management(outputFC, "ID;GRIDCODE")
except Exception, err:
    gp.AddError(str(err))
    gp.AddError(gp.getmessages(2))