# ---------------------------------------------------------------------------
# RasterCollectionToPoints.py
# Created on: Fri Oct 03 2008 02:30:52 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Set the necessary product code
gp.SetProduct("ArcInfo")

# Check out any necessary licenses
gp.CheckOutExtension("spatial")

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Spatial Analyst Tools.tbx")
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Conversion Tools.tbx")
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")


# Local variables...
Raster_Layer = ""
Output_point_features = ""
Output_table = ""
Input_rasters = ""
Output_Layer_Name = ""

# Process: Raster to Point...
gp.RasterToPoint_conversion(Raster_Layer, Output_point_features, "")

# Process: Sample...
gp.Sample_sa(Input_rasters, Output_point_features, Output_table, "NEAREST")

# Process: Join Field...
gp.JoinField_management(Output_point_features, "", Output_table, "", "")

